# Generated by Django 4.0.6 on 2022-09-10 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dromru', '0002_price_adsfilter_users_filters_alter_adsfilter_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsfilter',
            name='default_start',
            field=models.BooleanField(default=True, verbose_name='Запуск'),
        ),
        migrations.AlterField(
            model_name='adsfilter',
            name='filter_word',
            field=models.CharField(blank=True, max_length=150, verbose_name='Слова которые должны быть в объявлении (Через пробел)'),
        ),
        migrations.AlterField(
            model_name='adsfilter',
            name='no_price_skip',
            field=models.BooleanField(blank=True, default=False, verbose_name='Пропускать объявления без цены'),
        ),
        migrations.AlterField(
            model_name='adsfilter',
            name='recheck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dromru.price', verbose_name='Период проверки'),
        ),
        migrations.AlterField(
            model_name='adsfilter',
            name='send_email',
            field=models.BooleanField(default=True, verbose_name='Отправка на E-mail'),
        ),
        migrations.AlterField(
            model_name='adsfilter',
            name='send_tg',
            field=models.BooleanField(default=False, verbose_name='Отправка в TG'),
        ),
        migrations.AlterField(
            model_name='adsfilter',
            name='stop_word',
            field=models.CharField(blank=True, max_length=150, verbose_name='Стоп слова (Через пробел)'),
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg', models.TextField(max_length=50, verbose_name='Телеграм')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
